### PR TITLE
add gas weight conversion for N2O to N and fix weight conversion for SC-SF6

### PR DESCRIPTION
**Pull request by ckingdon95**
I think that computing the social cost of N2O was previously returning the social cost per ton of N not N2O, because the units in the emissions component are in tons of N. This PR normalizes the pulse size to be in tons of N2O instead

### CODE REVIEW

**Comment by ckingdon95** [comment]
@davidanthoff I also just noticed in the documentation that the units for SF6 emissions in FUND are "million metric tonnes of carbon dioxide equivalent." Does that mean that in order to report the SC-SF6 in units of dollars per ton of SF6, we would actually need to multiple by some GWP? (i.e., is the compute_sf6 function currently returning the value in $/ton of CO2e?)

**Comment by lrennels** [comment]
@davidanthoff I think it's worth reviewing this and either merging or closing.  From my read of it I think the calculation is actually already correct and don't need to be adjusted, but could use another pair of eyes. I'm not sure about the SC-SF6 question.

**Comment by lrennels** [comment]
use these to gut-check from
source: http://www.economics-ejournal.org/dataset/PDFs/journalarticles_2014-31.pdf

image
image

**Comment by lrennels** [comment]
use these to gut-check from
source: http://www.economics-ejournal.org/dataset/PDFs/journalarticles_2014-31.pdf

image
image
image

**Pull request merged**
