### PR TITLE
Update run_sim sim kywargs

### PR DESCRIPTION
**Pull request by lrennels**
@davidanthoff this update keeps us consistent with the mcs machinery.  We are trying to keep these changes to a minimum, but this one is important for clarity and generalization.  It also may be worth tagging a new release of MimiFUND here and then updating the registry (I can do that too if you give me access) so that dependency tests run smoothly in Mimi.

### CODE REVIEW

**Comment by davidanthoff** [comment]
This seems to generate a lot of output on CI? And CI fails :)

**Comment by lrennels** [comment]
@davidanthoff sorry, that's because I hadn't yet tagged a new version of Mimi with the mcs updates.  I can do that now that Rich has approved the PR, and then the CI should pass.

**Comment by lrennels** [comment]
@davidanthoff ok if you restart the build I think it should pass now

**Comment by davidanthoff** [comment]
Ok, I restarted! Btw., one trick to restart a build yourself is to close and then open the PR again, that triggers a new build :)

**Pull request merged**
