### PR TITLE
Updates for Mimi v1.0.0

### PR DESCRIPTION
**Pull request by ckingdon95**
This is currently WIP, tests will fail until the version of Mimi is updated

### CODE REVIEW

**Comment by lrennels** [comment]
```
# Test with a modified model
m_high_cs = MimiFUND.get_model()
update_param!(m_high_cs, :climatesensitivity, 5)
scc6 = MimiFUND.compute_scco2(m_high_cs, year=2020, last_year=2300)
@test scc6 > scc2 # test that it's higher than the default because of a higher climate sensitivity
```
the `update_param!` call gives this error:
```
julia> update_param!(m_high_cs, :climatesensitivity, 5)
ERROR: Cannot update parameter; climatesensitivity not found in composite's external parameters.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #_update_param!#51(::Bool, ::typeof(Mimi._update_param!), ::Mimi.ModelDef, ::Symbol, ::Int64, ::Bool) at /Users/lisarennels/.julia/dev/Mimi/src/core/connections.jl:532
 [3] #update_param!#139 at ./none:0 [inlined]
 [4] update_param!(::Model, ::Symbol, ::Int64) at /Users/lisarennels/.julia/dev/Mimi/src/core/delegate.jl:55
 [5] top-level scope at REPL[54]:1
```

**Comment by davidanthoff** [comment]
I bet this is related to the fact that `climatesensitivity` has a default value in the component definition. Maybe parameters in components that have a default value for some reason no longer end up in the external parameter list of the model def? They should, though. @rjplevin any thoughts on this?

**Comment by rjplevin** [comment]
I didn't specifically test `update_param!`, but since Mimi tests were passing I thought it was ok. I think the first step should be to write a test for this.

The intention was that if a default exists and no explicit value is set (which also creates an external param) _and_ the parameter is not linked to a variable, an external parameter is created for the default value.

**Comment by davidanthoff** [comment]
> The intention was that if a default exists and no explicit value is set (which also creates an external param) and the parameter is not linked to a variable, an external parameter is created for the default value.

Yes, that sounds right, but I think that is not what is happening right now. I created a test for this (that currently fails): https://github.com/mimiframework/Mimi.jl/pull/678

**Comment by ckingdon95** [comment]
I'm going to move the conversation about this error and functionality to the PR David started mimiframework/Mimi.jl#678

**Comment by davidanthoff** [comment]
So this branch now passes in `test_all_models.jl`, hurray!

**Pull request merged**
